### ISSUE TITLE
Expose ply type in python

### ISSUE THREAD

**Issue by janvonrickenbach** [ansys/pydpf-composites#451]
* Check if it is already possible to get the ply type in python
* If no add functionality in the backend
* Extend the custom failure criteria example to show how the data can be filtered by ply type

Note: 2024R2 milestone only applies if the ply type is already available in python.

**Comment by janvonrickenbach** [comment]
Currently not supported by the eng_data::ans_mat_property_field_provider since this is a string property.

**Comment by janvonrickenbach** [comment]
@roosre Can this be closed?

**Comment by roosre** [comment]
Was closed by PR #465
https://github.com/ansys/pydpf-composites/pull/465
