### ISSUE TITLE
Implement ARM Test to verify workflows using the unified installer

### ISSUE THREAD

**Issue by roosre** [ansys/pydpf-composites#49]
Add ARM test which installs the public package and runs a failure analysis with the dpf server of the unified installer

- [ ] test standalone installer (local server)

- Use model in POST:Core/POST_COMPOSITES_FAILURE/POST_COMPOSITES_FAILURE_010 to test assembly
  Test these features
- [ ] Test failure plot: for the entire model or just a sub-part of the assembly
- [ ] Test sampling point: test on different sub-part of the assembly

**Comment by janvonrickenbach** [comment]
Created task 803214 in TFS

**Comment by roosre** [comment]
@janvonrickenbach , task 803214 in TFS is closed. Can we close this issue as well? René

**Comment by janvonrickenbach** [comment]
A test has been added for the inprocess server. We should also create a test for starting the grpc server.
